In [1]:
import numpy as np 
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
new1=np.concatenate((arr1,arr2),axis=0)
print(new1)

arr1= np.array([[1,2],[3,6]])
arr2= np.array([[4,5],[7,8]])
new2=np.concatenate((arr1,arr2),axis=1)
print(new2)

[1 2 3 4 5 6]
[[1 2 4 5]
 [3 6 7 8]]
