In [2]:
import numpy as np
arr =np.array([1,2,3,4,5,6,7])
print(arr)
print(np.delete(arr,0, axis=0))


[1 2 3 4 5 6 7]
[2 3 4 5 6 7]


In [4]:
arr_2d=np.array([[1,2,3],[4,5,6]])
new_arr=np.delete(arr_2d,0,axis=0)
print(new_arr)

[[4 5 6]]
