In [8]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
new_arr=np.insert(arr, 1, [7,8], axis=1)
print(new_arr)
new_arr2=np.insert(arr, 1, [7,8,9], axis=0)
print(new_arr2)

[[1 2 3]
 [4 5 6]]
[[1 7 2 3]
 [4 8 5 6]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
