In [2]:
import numpy as np
arr =np.array([12,3,4])
print(arr*2)

[24  6  8]


In [5]:
# 1d to 2d array braodcasting 

import numpy as np
matrix= np.array([[1,2,3],[4,5,6]])
vector =np.array([10,20,30])
result = matrix+vector
print(result)

[[11 22 33]
 [14 25 36]]
