In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1])

2


In [3]:
print(arr[4])

5


In [6]:
# Slicing
print(arr[1:4:2])

[2 4]


In [13]:
print(arr[1:4])
print(arr[:5])
print(arr[::2])
print(arr[::-1])

[2 3 4]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


In [14]:
# Fancy indexing
print(arr[[0,2,4]])

[1 3 5]


In [4]:
# Filtering indexing / boolean masking
import numpy as np
arr = np.array([1,20,33,42,5])
print(arr[arr>25])

[33 42]
