In [1]:
# one dimensional Array
import numpy as np
arr_1d=np.array([10,20,30,40,50])
print(arr_1d)

[10 20 30 40 50]


In [3]:
# Two dimensional Array
arr_2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# multi dimensional Array
# matrix
matrix= np.array([[2,4,6],[8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]


In [1]:
# creating array from list 
# np.array([ele1,ele2,ele3])
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)


[10 20 30 40 50]


In [3]:
# with default values 
import numpy as np
zeroes_array=np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [4]:
import numpy as np
ones_array=np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:

filled_array=np.full((2,2),7)
print(filled_array)

[[7 7]
 [7 7]]
