In [2]:
import numpy as np
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [5]:
# Creating identity matrices 
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
